### ISSUE TITLE
Issues about mysql connection

### ISSUE THREAD

**Issue by LoveFrea** [lucavinci/bungeeban#14]
Error occur when plugin enabled:
`18:50:56 [警告] Exception encountered when loading plugin: BungeeBan
java.lang.IllegalArgumentException: No enum constant de.lucavinci.bungeeban.util.SQL.DriverType.MySQL
    at java.lang.Enum.valueOf(Unknown Source)
    at de.lucavinci.bungeeban.util.SQL$DriverType.valueOf(SQL.java:182)
    at de.lucavinci.bungeeban.util.ConfigManager.init(ConfigManager.java:22)
    at de.lucavinci.bungeeban.BungeeBan.onEnable(BungeeBan.java:36)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:112)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`
When disabled:
`18:49:41 [严重] Exception disabling plugin BungeeBan
java.lang.NullPointerException
	at de.lucavinci.bungeeban.BungeeBan.onDisable(BungeeBan.java:47)
	at net.md_5.bungee.BungeeCord$4.run(BungeeCord.java:421)`

**Comment by Azn9** [comment]
Replace "driver: 'MySQL'" by "driver: 'MYSQL'" in the config.yml file.
